#!/bin/bash

UUT="${1:-acq2106_188}"
POST=${POST:-1000000}

if [ ! -e ../acq400_hapi ]; then
	echo "ERROR ../acq400_hapi NOT FOUND"
	exit 1
else
	HAPI=$(dirname $PWD)/acq400_hapi		
	export PYTHONPATH=$PYTHONPATH:$HAPI
	echo $PYTHONPATH
fi

#export SITECLIENT_TRACE=1
python3 $HAPI/user_apps/acq400/acq400_upload.py --save_data ACQ494 \
	--post=$POST --trg=int,rising --auto_soft_trigger 1 \
	--trace_upload=1 --demux=0 --capture=1 ${UUT}
( cd ACQ494
for uut in $UUT; do
	rm -f gpx2*.dat
	../gpx2_decode --save=1 --TAI128=1 --1588v2=1 < ${uut}_CH00
	ls -l gpx2*.dat
	sha1sum gpx2*.dat
	mkdir -p $uut; mv gpx2* $uut
	( cd $uut
#		for file in gpx2*dat; do
#		../../gpx2_plot_stops.py --times=$file ${UUT}
#done
#		for file in gpx2*TAI128; do
#			../../plot.TAI128.py $file ${UUT}
#		done
		for file in gpx2*1588v2; do
			../../plot.1588v2.py $file ${UUT}
		done
	)
done
)
ls -lR ACQ494



